### ISSUE TITLE
support list of models to archive outside of dependant: destroy

### ISSUE THREAD

**Issue by aleccool213** [dorner/rails-archiver#3]
- In some cases, we want to archive a model which has a relationship with the base archived model which does not have `dependant: destroy` as an option.
- Support a list of tables which can override the filter in [`get_associations`](https://github.com/dorner/rails-archiver/blob/master/lib/rails-archiver/archiver.rb#L104).

**Comment by dorner** [comment]
The fact that `get_associations` is a method means it can be overridden in child classes. So we can subclass Archiver and redefine this method in the subclass.
